# Generated by Django 3.2.5 on 2021-07-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Username', models.CharField(max_length=150)),
                ('Register_num', models.CharField(max_length=150)),
                ('Dob', models.CharField(max_length=100)),
                ('Cutoff', models.FloatField()),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
