# Generated by Django 3.2.5 on 2021-08-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='Cutoff',
        ),
        migrations.RemoveField(
            model_name='table',
            name='Dob',
        ),
        migrations.RemoveField(
            model_name='table',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='table',
            name='Register_num',
        ),
        migrations.RemoveField(
            model_name='table',
            name='Username',
        ),
        migrations.AddField(
            model_name='table',
            name='data',
            field=models.JSONField(db_index=True, null=True),
        ),
    ]
